name: Testar Aplicação Tkinter + Kanban
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
    - name: Instalar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Instalar dependências (se houver)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
    - name: Rodar testes com unittest
      run: |
        python -m unittest discover -s tests -p "*.py"